[book]
authors = ["kraftnix"]
language = "en"
src = "."
title = "provision-nix Documentation"

[output.html]
# theme = "my-theme"
# my theme is a modified ayu, overriden on navy
site-url = "/"
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
no-section-label = false
git-repository-url = "https://github.com/kraftnix/provision-nix"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://github.com/kraftnix/provision-nix/_edit/main/docs/{path}"
# use-site-url-as-root = true
# additional-css = ["theme/pagetoc.css"]
# additional-js  = ["theme/pagetoc.js"]

# [output.html.fold]
# enable = true
# level = 1

[output.html.print]
enable = false  # big single page; don't need that

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.linkcheck]
follow-web-links = false # no Internet during the build

[preprocessor.variables]
use_env = true
[preprocessor.variables.variables]
git_file_base_url = "https://github.com/kraftnix/provision-nix/tree/master/"

# [preprocessor.cmdrun]

# [preprocessor.repo_url]
# command = "echo 'https://github.com/kraftnix/provision-nix'"
